# Generated by Django 2.0.1 on 2018-02-19 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20180215_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, choices=[('g', 'General'), ('h', 'Household'), ('e', 'Electronics'), ('f', 'Food'), ('c', 'Clothing')], max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='item_close',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_created',
            field=models.DateTimeField(editable=False),
        ),
    ]
